import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import QueryProvider from './query/query-client/query-client-provider';
import NavbarMovies from './movies/navbar/navbar-movies-';
import FooterMovies from './footer/page';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Movies',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarMovies />
        <QueryProvider>{children}</QueryProvider>
        <FooterMovies />
      </body>
    </html>
  );
}
